---
title: Giovana Ansoain
timezone: UTC
collections:
  mediums:
    title: Mediums
    output: false
  pages:
    title: Pages
    output: true
  partners:
    title: Partners
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:name"
  testimonials:
    title: Testimonials
    output: false
  uploads:
    title: Uploads
    output: false
email: ola@giovana.cc
phone: "+55 11 97675 7107"
description: Giovana Ansoain Portfolio. Buscamos soluções criativas com processo de
  design para criar inovação.
meta_keywords: assessoria, agilidade, inovacao
baseurl: 
url: 
markdown: kramdown
plugins:
- jekyll-feed
sass:
  sass_dir: "/assets/css"
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
